<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <UseMonoGame>true</UseMonoGame>
    <MonoGamePlatform>DesktopGL</MonoGamePlatform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.3" />
    <PackageReference Include="MonoGame.Library.OpenAL" Version="1.23.1.11" />
    <PackageReference Include="MonoGame.Library.SDL" Version="2.32.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="SpriteFontPlus.MonoGame" Version="0.7.0.22" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Content\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Content\axe.png" />
    <None Remove="Content\cropStage0.png" />
    <None Remove="Content\cropStage1.png" />
    <None Remove="Content\cropStage2.png" />
    <None Remove="Content\cropStage3.png" />
    <None Remove="Content\cropStage4.png" />
    <None Remove="Content\DefaultFont.mgcb" />
    <None Remove="Content\Hoe.png" />
    <None Remove="Content\NPC.png" />
    <None Remove="Content\player.png" />
    <None Remove="Content\Tilesheet.png" />
    <None Remove="Content\Tut.png" />
    <None Remove="Content\wateringCan.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Content\axe.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Hoe.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\NPC.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\wateringCan.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Content\cropStage0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\cropStage1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\cropStage2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\cropStage3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\cropStage4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\player.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Tilesheet.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Tut.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>

  </ItemGroup>

	<ItemGroup>
	  <None Update="Content\DefaultFont.xnb">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
